name: ext-swoole

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# swoole-src
    - name: checkout swoole
      uses: actions/checkout@v2
      with:
        path: swoole-src
    - name: compile swoole-src
      working-directory: swoole-src
      run: |
        phpize
        ./configure \
        --enable-sockets \
        --enable-mysqlnd \
        --enable-http2 \
        --enable-debug-log
        make -j
# ext-async
    - name: checkout ext-async
      uses: actions/checkout@v2
      with:
        repository: swoole/ext-async
        path: ext-async
    - name: compile ext-async
      working-directory: ext-async
      run: |
        phpize
        ./configure
        make -j
