name: ext-swoole

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# debug
    - name: debug
      run: ls -al; \
           which phpize;
# swoole-src
    - name: checkout swoole
      uses: actions/checkout@v2
      with:
        path: swoole-src
    - name: compile swoole-src
      run: cd ${GITHUB_WORKSPACE}/swoole-src && \
           phpize && \
           ./configure \
           --enable-sockets \
           --enable-mysqlnd \
           --enable-http2 \
           --enable-debug-log && \
           make -j
# ext-async
    - name: checkout ext-async
      uses: actions/checkout@v2
      with:
        repository: swoole/ext-async
        path: ext-async
    - name: compile ext-async
      run: cd ${GITHUB_WORKSPACE}/ext-async && \
           phpize && \
           ./configure && \
           make -j
